spring.application.name=student-course-registration

spring.datasource.url=jdbc:h2:file:C:/Users/LabibO/IdeaProjects/internship program/student-course-registration/data/student-registration;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console